# config.yaml

# ===============================
# Data Configuration
# ===============================
data:
  # Directory containing processed CSV files for NASDAQ 100 stocks
  processed_data_dir: "C:/Users/colme/.quantlib/data/nasdaq100/processed_data/"

  # Sequence length for time series data
  seq_len: 10

  # List of feature column names to use; set to null to use all available features except 'Date' and 'Target'
  features_to_use: null  # Example: ["Open", "High", "Low", "Close", "Volume"]

  # Name of the target column to predict
  target_column: "Close"

  # Number of splits for TimeSeriesSplit cross-validation
  n_splits: 5

  # Proportion of training data to use for validation within each fold
  valid_size: 0.1

# ===============================
# Model Configuration
# ===============================
model:
  # Feature dimension (number of input features); dynamically set based on data
  fea_dim: 24

  # Number of output channels for the CNN layer
  cnn_dim: 128  # Increased from 64 to leverage more GPU memory

  # Kernel size for the CNN layer
  cnn_kernel_size: 3

  # Hidden dimension for the RNN layer
  rnn_dim: 128  # Increased from 64 to leverage more GPU memory

  # Number of duplicate RNN layers (if applicable)
  rnn_dups: 3

  # Number of stacked RNN layers
  rnn_layers: 2

  # Dropout rate to prevent overfitting
  dropout: 0.2

# ===============================
# Training Configuration
# ===============================
training:
  # Total number of training epochs
  n_epochs: 200

  # Learning rate for the optimizer
  lr: 0.001

  # Early stopping patience (number of epochs with no improvement after which training will be stopped)
  early_stop: 20

  # Loss function to optimize
  loss: "mse"  # Options: "mse", "mae", etc.

  # Optimizer to use
  optimizer: "adam"  # Options: "adam", "sgd", etc.

  # Batch size for training
  batch_size: 128  # Increased from 32 to utilize more GPU memory

  # Number of worker subprocesses for data loading
  num_workers: 12  # Set based on CPU cores

  # Random seed for reproducibility
  seed: 42

# ===============================
# Device Configuration
# ===============================
device:
  # GPU index to use (set to -1 to use CPU)
  GPU: 0

# ===============================
# Output Configuration
# ===============================
output:
  # Directory to save log files
  logs_dir: "logs"

  # Directory to save generated plots
  plots_dir: "C:/Users/colme/.quantlib/data/nasdaq100/plots"

  # Directory to save trained model checkpoints
  models_dir: "models"
