# config.yaml

# Data parameters
data:
  processed_data_dir: "~/.quantlib/data/nasdaq100/processed_data/"
  seq_len: 10
  batch_size: 32
  test_size: 0.2
  valid_size: 0.1  # Fraction of training data to use for validation

# Model parameters
model:
  fea_dim: null  # Will be set dynamically based on the data
  cnn_dim: 256
  cnn_kernel_size: 3
  rnn_dim: 256
  rnn_dups: 3
  rnn_layers: 2
  dropout: 0.5  # Increased dropout rate

# Training parameters
training:
  n_epochs: 100
  lr: 0.0005  # Reduced learning rate
  early_stop: 15  # Increased early stopping patience
  loss: "mse"
  optimizer: "adam"
  seed: 42

# Device configuration
device:
  GPU: 0  # Set to -1 for CPU

# Output paths
output:
  model_save_path: "krnn_model.pth"
